"""New Revision

Revision ID: 31a7657c05ea
Revises: 4743b945570c
Create Date: 2024-07-17 15:43:51.533173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31a7657c05ea'
down_revision: Union[str, None] = '4743b945570c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('json_table', sa.Column('state', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('json_table', 'state')
    # ### end Alembic commands ###
